/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Document
         * @description Upload a document, save to storage/{content_id}/, and index.
         *
         *     If content_id given → saved under storage/{content_id}/{filename}.
         *     Otherwise → saved to data/uploads/ with UUID prefix.
         */
        post: operations["upload_document_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/index-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Index Batch
         * @description Index all indexable documents in storage/{content_id}/.
         *
         *     Non-indexable files (video, audio, images) are silently skipped.
         */
        post: operations["index_batch_documents_index_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/browse/contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contents */
        get: operations["get_contents_browse_contents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/browse/contents/{content_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Files
         * @description List ALL files for a content_id — documents, videos, audio, etc.
         *     Documents get an `indexed` flag from Qdrant.
         */
        get: operations["get_files_browse_contents__content_id__files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Question */
        post: operations["ask_question_chat_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Feedback */
        post: operations["submit_feedback_chat_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchFileResult */
        BatchFileResult: {
            /** Filename */
            filename: string;
            /** Content Id */
            content_id: string;
            /** Chunks Created */
            chunks_created: number;
            /** Points Stored */
            points_stored: number;
            /** Status */
            status: string;
        };
        /** BatchIndexRequest */
        BatchIndexRequest: {
            /** Content Id */
            content_id: string;
        };
        /** BatchIndexSummary */
        BatchIndexSummary: {
            /** Total Files */
            total_files: number;
            /** Indexed */
            indexed: number;
            /** Skipped */
            skipped: number;
            /** Errors */
            errors: string[];
            /** Results */
            results: components["schemas"]["BatchFileResult"][];
        };
        /** Body_upload_document_documents_upload_post */
        Body_upload_document_documents_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Content Id */
            content_id?: string | null;
        };
        /** ContentListResponse */
        ContentListResponse: {
            /** Contents */
            contents: string[];
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Interaction Id */
            interaction_id: string;
            /**
             * Rating
             * @enum {string}
             */
            rating: "membantu" | "cukup" | "tidak_membantu";
            /** Issues */
            issues?: string[];
            /** Comment */
            comment?: string | null;
        };
        /** FileInfo */
        FileInfo: {
            /** Filename */
            filename: string;
            /** Content Id */
            content_id: string;
            /** Size Bytes */
            size_bytes: number;
            /** Size Display */
            size_display: string;
            /** Category */
            category: string;
            /** Is Indexable */
            is_indexable: boolean;
            /** Indexed */
            indexed: boolean;
        };
        /** FileListResponse */
        FileListResponse: {
            /** Content Id */
            content_id: string;
            /** Files */
            files: components["schemas"]["FileInfo"][];
            /** Total Files */
            total_files: number;
            /** Total Indexable */
            total_indexable: number;
            /** Total Indexed */
            total_indexed: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndexResponse */
        IndexResponse: {
            /** Source File */
            source_file: string;
            /** Elements Parsed */
            elements_parsed: number;
            /** Chunks Created */
            chunks_created: number;
            /** Points Stored */
            points_stored: number;
            /** Content Id */
            content_id: string | null;
        };
        /** QueryRequest */
        QueryRequest: {
            /** Question */
            question: string;
            /** Session Id */
            session_id?: string | null;
            /** Content Id */
            content_id?: string | null;
            /** Source Filter */
            source_filter?: string | null;
        };
        /** QueryResponse */
        QueryResponse: {
            /** Answer */
            answer: string;
            /** Sources */
            sources: components["schemas"]["SourceInfo"][];
            /** Recommendations */
            recommendations: string[];
            /** Session Id */
            session_id: string;
            /** Interaction Id */
            interaction_id?: string | null;
        };
        /** SourceInfo */
        SourceInfo: {
            /** Index */
            index: number;
            /** Source File */
            source_file?: string | null;
            /** Page Number */
            page_number?: number | null;
            /** Element Type */
            element_type?: string | null;
            /** Content Id */
            content_id?: string | null;
            /** Rerank Score */
            rerank_score?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_document_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_batch_documents_index_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchIndexRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchIndexSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contents_browse_contents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentListResponse"];
                };
            };
        };
    };
    get_files_browse_contents__content_id__files_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_question_chat_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_chat_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
